name: Docker Image CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v3
            -
                name: Docker meta
                id: meta
                uses: docker/metadata-action@v4
                with:
                    images: happypaul/liberandum
            -
                name: Login to DockerHub
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            -
                name: Build and push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
            -
                name: Patch the docker-compose file
                run: sed -i 's#build:\ \.#image:\ ${{ steps.meta.outputs.tags }}#g' docker-compose.yaml
            -
                name: Start Dependancies
                run: docker-compose up -d database
            -
                name: Check the coding standards
                run: docker-compose run --rm app yarn run lint
            -
                name: Populate the database
                run: docker-compose run --rm app yarn run schema:push
            -
                name: Test the Docker image
                run: docker-compose run --rm app yarn run test